"""add stories front matter: author, tags, logline, summary

These were generated by an LLM on every export and written straight into
summarize.txt without ever being stored, so the same book could get a different
logline each time it was exported, the API could not serve them without reading a
file, and image regeneration — which runs no export — had none of them at all.

Revision ID: 0006_add_story_front_matter
Revises: 0005_add_chapter_traces
Create Date: 2026-08-12 00:00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0006_add_story_front_matter"
down_revision: Union[str, None] = "0005_add_chapter_traces"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("stories", sa.Column("author", sa.String(), nullable=True))
    op.add_column("stories", sa.Column("tags", sa.JSON(), nullable=True))
    op.add_column("stories", sa.Column("logline", sa.Text(), nullable=True))
    op.add_column("stories", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("stories", sa.Column("cast_blurbs", sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column("stories", "cast_blurbs")
    op.drop_column("stories", "summary")
    op.drop_column("stories", "logline")
    op.drop_column("stories", "tags")
    op.drop_column("stories", "author")
