"""initial schema

Revision ID: 01d74b032ee3
Revises: 
Create Date: 2026-08-09 16:32:02.909818
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01d74b032ee3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('target_words', sa.Integer(), nullable=False),
    sa.Column('words_per_chapter', sa.Integer(), nullable=False),
    sa.Column('current_words', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('last_checkpoint_chapter', sa.Integer(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('planning_verified', sa.Boolean(), nullable=True),
    sa.Column('new_graph_built', sa.Boolean(), nullable=True),
    sa.Column('new_graph_verified', sa.Boolean(), nullable=True),
    sa.Column('source_graph_verified', sa.Boolean(), nullable=True),
    sa.Column('story_bible', sa.Text(), nullable=True),
    sa.Column('plot_outline', sa.Text(), nullable=True),
    sa.Column('world_bible', sa.Text(), nullable=True),
    sa.Column('source_chapter_count', sa.Integer(), nullable=True),
    sa.Column('source_spirit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('chapter_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'chapter_number', name='uq_chapter_summary')
    )
    op.create_table('chapter_verify_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('blueprint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'number', name='uq_chapter_number')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('profile_md', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'name', name='uq_character_name')
    )
    op.create_table('continuity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_chapter', sa.Integer(), nullable=True),
    sa.Column('critical_issues', sa.JSON(), nullable=True),
    sa.Column('minor_issues', sa.JSON(), nullable=True),
    sa.Column('batch_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id')
    )
    op.create_table('foreshadowing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('fid', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('planted_chapter', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payoff_chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'fid', name='uq_foreshadow')
    )
    op.create_table('planning_verify_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('artifact', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_planner_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_chapter', sa.Integer(), nullable=True),
    sa.Column('pacing_note', sa.Text(), nullable=True),
    sa.Column('characters_to_watch', sa.JSON(), nullable=True),
    sa.Column('threads_to_resolve', sa.JSON(), nullable=True),
    sa.Column('outline_adjustments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id')
    )
    op.create_table('state_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('graph_type', sa.String(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('chapter_from', sa.Integer(), nullable=True),
    sa.Column('chapter_to', sa.Integer(), nullable=True),
    sa.Column('trigger_event_key', sa.String(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_graph_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('graph_type', sa.String(), nullable=False),
    sa.Column('node_key', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('chapter_introduced', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'graph_type', 'node_key', name='uq_graph_node')
    )
    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at_chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'entity_type', 'entity_key', 'field', name='uq_world_state_row')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_state')
    op.drop_table('story_graph_nodes')
    op.drop_table('story_graph_edges')
    op.drop_table('state_log')
    op.drop_table('smart_planner_state')
    op.drop_table('planning_verify_log')
    op.drop_table('foreshadowing')
    op.drop_table('continuity_log')
    op.drop_table('characters')
    op.drop_table('chapters')
    op.drop_table('chapter_verify_log')
    op.drop_table('chapter_summaries')
    op.drop_table('stories')
    # ### end Alembic commands ###
